$(info Makefile.dep picoarch is $(PICOARCH))

ifeq ($(PICOARCH),RISCV)
USEPKG += picosdk

include $(RIOTCPU)/riscv_common/Makefile.dep

else ifeq ($(PICOARCH),ARM)

USEPKG += picosdk

include $(RIOTCPU)/cortexm_common/Makefile.dep

endif
