CPU_CORE    := rv32
CPU_FAM     := RP2350_RISCV
CPU_ARCH    = rv32
CPU_MODEL   = rp2350_riscv

include $(RIOTCPU)/riscv_common/Makefile.features

FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_uart
