CPU_MODEL = esp32c6_mini_1x

# common board and CPU features
include $(RIOTBOARD)/common/esp32c6/Makefile.features

# additional features provided by the board
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_spi

# unique features provided by the board
FEATURES_PROVIDED += esp_jtag
